"""add unique constraint to sales game_id

Revision ID: cdf0621ebdb0
Revises: aab6cb811d9a
Create Date: 2026-03-01 16:19:08.655342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf0621ebdb0'
down_revision: Union[str, None] = 'aab6cb811d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sales_game_id_unique', 'sales', ['game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_game_id_unique', 'sales', type_='unique')
    # ### end Alembic commands ###
